# Generated by Django 6.0.3 on 2026-04-02 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Human context about the brand. Not used by Claude.')),
                ('signature', models.JSONField(blank=True, help_text='Extracted tone-of-voice signature with 5 characteristics.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('filename', models.CharField(help_text='Original filename for display.', max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Plain Text'), ('png', 'PNG Image')], max_length=10)),
                ('extracted_text', models.TextField(help_text='Plain text extracted from the file at upload time.')),
                ('truncated', models.BooleanField(default=False, help_text='True if extracted_text was cut at 12,000 characters.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.brand')),
            ],
        ),
    ]
