"""
REST API views for the Tone-of-Voice platform.

BrandViewSet   — full CRUD + /extract/ + /transform/ custom actions
DocumentViewSet — list, upload, delete; nested under /api/brands/{brand_id}/documents/
"""

import logging
from typing import Any

from django.shortcuts import get_object_or_404
from drf_spectacular.utils import OpenApiResponse, extend_schema
from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.parsers import JSONParser, MultiPartParser
from rest_framework.request import Request
from rest_framework.response import Response

from core.models import Brand, Document
from core.serializers import BrandSerializer, DocumentSerializer
from core.services.claude import ClaudeServiceError, extract_signature, transform_text
from core.services.extraction import extract_text

logger = logging.getLogger(__name__)

ALLOWED_EXTENSIONS: frozenset[str] = frozenset({"pdf", "docx", "txt", "png"})
MAX_UPLOAD_BYTES: int = 20 * 1024 * 1024  # 20 MB

# Magic-byte prefixes for binary formats.
MIME_MAGIC: dict[str, bytes] = {
    "pdf": b"%PDF",
    "png": b"\x89PNG",
    "docx": b"PK",  # DOCX is a ZIP archive
}


def _validate_file(file: Any) -> tuple[str, str | None]:
    """Validate extension, file size, and magic bytes.

    Parameters
    ----------
    file:
        An uploaded file object (``InMemoryUploadedFile`` or ``TemporaryUploadedFile``).

    Returns
    -------
    tuple[str, str | None]
        ``(extension, error_message)``. ``error_message`` is ``None`` when the file is valid.
    """
    name: str = getattr(file, "name", "") or ""
    ext = name.rsplit(".", 1)[-1].lower() if "." in name else ""

    if ext not in ALLOWED_EXTENSIONS:
        return ext, f"Unsupported file type '.{ext}'. Accepted: pdf, docx, txt, png."

    if file.size > MAX_UPLOAD_BYTES:
        return ext, "File exceeds the 20 MB size limit."

    if ext in MIME_MAGIC:
        header = file.read(8)
        file.seek(0)
        if not header.startswith(MIME_MAGIC[ext]):
            return ext, f"File content does not match the '{ext}' format."

    return ext, None


# ---------------------------------------------------------------------------
# Brand ViewSet
# ---------------------------------------------------------------------------

class BrandViewSet(viewsets.ModelViewSet):
    """Full CRUD for Brand objects plus /extract/ and /transform/ custom actions.

    Standard routes (auto-generated by DefaultRouter):
        GET    /api/brands/          — list
        POST   /api/brands/          — create
        GET    /api/brands/{id}/     — retrieve
        PATCH  /api/brands/{id}/     — partial update (name / description only)
        DELETE /api/brands/{id}/     — destroy (cascades to documents)

    Custom actions:
        POST /api/brands/{id}/extract/   — extract tone-of-voice signature via Claude
        POST /api/brands/{id}/transform/ — rewrite text in the brand's voice
    """

    queryset = Brand.objects.all()
    serializer_class = BrandSerializer
    http_method_names = ["get", "post", "patch", "delete", "head", "options"]

    @extend_schema(
        request=None,
        responses={
            200: OpenApiResponse(description="Signature extracted successfully"),
            400: OpenApiResponse(description="No documents uploaded for this brand"),
            502: OpenApiResponse(description="Claude API failure"),
        },
        summary="Extract tone-of-voice signature from uploaded documents",
    )
    @action(detail=True, methods=["post"], url_path="extract")
    def extract(self, request: Request, pk: int = None) -> Response:
        """Analyze all uploaded documents with Claude and save the tone-of-voice signature.

        Request body: empty ``{}``.
        Returns 400 if no documents exist, 502 on Claude API failure.
        """
        brand = self.get_object()
        documents = list(brand.documents.all())

        if not documents:
            return Response(
                {"error": "No documents found for this brand. Upload at least one document before extracting."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        previous_existed = brand.signature is not None
        texts = [doc.extracted_text for doc in documents]
        truncated_count = sum(1 for doc in documents if doc.truncated)

        try:
            signature = extract_signature(texts)
        except ClaudeServiceError as exc:
            return Response({"error": str(exc)}, status=status.HTTP_502_BAD_GATEWAY)

        brand.signature = signature
        brand.save(update_fields=["signature"])

        return Response({
            "brand_id": brand.pk,
            "previous_signature_existed": previous_existed,
            "signature": signature,
            "documents_analyzed": len(documents),
            "documents_truncated": truncated_count,
        })

    @extend_schema(
        request={"application/json": {"type": "object", "properties": {"text": {"type": "string"}}, "required": ["text"]}},
        responses={
            200: OpenApiResponse(description="Text transformed successfully"),
            400: OpenApiResponse(description="Missing text field or no signature extracted yet"),
            502: OpenApiResponse(description="Claude API failure"),
        },
        summary="Rewrite text in the brand's tone-of-voice",
    )
    @action(detail=True, methods=["post"], url_path="transform")
    def transform(self, request: Request, pk: int = None) -> Response:
        """Rewrite user-supplied text applying the brand's stored tone-of-voice signature.

        Request body: ``{"text": "..."}``
        Returns 400 if no signature exists or ``text`` is missing, 502 on Claude failure.
        """
        brand = self.get_object()

        if not brand.signature:
            return Response(
                {"error": "No signature found for this brand. Run POST /extract/ first."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        text = (request.data.get("text") or "").strip()
        if not text:
            return Response(
                {"error": "Field 'text' is required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:
            transformed = transform_text(text, brand.signature)
        except ClaudeServiceError as exc:
            return Response({"error": str(exc)}, status=status.HTTP_502_BAD_GATEWAY)

        return Response({
            "brand_id": brand.pk,
            "original": text,
            "transformed": transformed,
            "original_char_count": len(text),
            "transformed_char_count": len(transformed),
            "signature_used": brand.signature,
        })


# ---------------------------------------------------------------------------
# Document ViewSet (nested under brands)
# ---------------------------------------------------------------------------

class DocumentViewSet(viewsets.ViewSet):
    """List, upload, and delete documents for a brand.

    Routes (registered manually in urls.py):
        GET    /api/brands/{brand_id}/documents/          — list
        POST   /api/brands/{brand_id}/documents/          — upload (multipart/form-data)
        DELETE /api/brands/{brand_id}/documents/{id}/     — destroy
    """

    parser_classes = [MultiPartParser, JSONParser]

    def list(self, request: Request, brand_id: int) -> Response:
        """List all documents uploaded for a brand.

        Returns 200 with a list of document objects, 404 if brand not found.
        """
        brand = get_object_or_404(Brand, pk=brand_id)
        docs = brand.documents.all()
        return Response(DocumentSerializer(docs, many=True).data)

    def create(self, request: Request, brand_id: int) -> Response:
        """Upload a document and extract its text immediately.

        Send as ``multipart/form-data`` with a ``file`` field.
        Accepted types: pdf, docx, txt, png. Max size: 20 MB.
        Returns 400 for invalid type, oversized file, or unreadable content.
        """
        brand = get_object_or_404(Brand, pk=brand_id)

        uploaded = request.FILES.get("file")
        if not uploaded:
            return Response({"error": "No file provided."}, status=status.HTTP_400_BAD_REQUEST)

        ext, error = _validate_file(uploaded)
        if error:
            return Response({"error": error}, status=status.HTTP_400_BAD_REQUEST)

        try:
            extracted, was_truncated = extract_text(uploaded, ext)
        except ValueError as exc:
            return Response({"error": str(exc)}, status=status.HTTP_400_BAD_REQUEST)

        uploaded.seek(0)
        doc = Document.objects.create(
            brand=brand,
            file=uploaded,
            filename=uploaded.name,
            file_type=ext,
            extracted_text=extracted,
            truncated=was_truncated,
        )

        return Response(DocumentSerializer(doc).data, status=status.HTTP_201_CREATED)

    def destroy(self, request: Request, brand_id: int, pk: int = None) -> Response:
        """Delete a document. Does not trigger re-extraction automatically.

        Returns 204 on success, 404 if not found.
        """
        brand = get_object_or_404(Brand, pk=brand_id)
        doc = get_object_or_404(Document, pk=pk, brand=brand)
        doc.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
